### ISSUE TITLE
 I'm having several problems installing the panel

### ISSUE THREAD

**Issue by crews1515** [AlexanderJLiu/IPTVM#7]
@AlexanderJLiu  I am facing several errors when installing the iptv panel every time I try to import the database from this error> # 1044 - Access denied for user 'id2662156_iptvm' @ '%' to database 'iptvm', when I enter the login panel appears these errors that are in the attached photo, I would like someone to help me with these problems.

image > https://i.imgur.com/8dGzCth.png .

**Comment by AlexanderJLiu** [comment]
@crews1515 The user  **id2662156_iptvm**  must have the privilege first.  You can try the following commands at the MySQL command line:

** GRANT ALL ON *.* TO 'id2662156_iptvm'@'%' WITH GRANT OPTION;
** FLUSH PRIVILEGES;

**Comment by crews1515** [comment]
@AlexanderJLiu Hello, I can solve the database error, but now I have several errors in the extension yiisoft, I tried to correct it every time a new error appears in yiisoft.

**Comment by btoplak** [comment]
@crews1515 Try to upgrade Yii framework (using Composer), it worked for me. Since I have installed a test app on Ubuntu 18.04 with PHP 7.2 I had to upgrade Yii and other stuff via Composer to get the site working. I hope that helps you ...

Now I have only one error page, for which I will open a separate issue ...

**Comment by crews1515** [comment]
@btoplak thanks for this tip, I will do the test and see if it works for me, because there appeared many errors in this panel.

**Comment by crews1515** [comment]
@btoplak even after updating yii I still get this error: Fatal error: ( Can not use 'Object' as class is as reserved in /var/www/html/IPTVM/vendor/yiisoft/yii2/base/Object.php on line 77 ), I wonder if you know how to solve it because I'm still a beginner in this.

**Comment by btoplak** [comment]
@crews1515 Yes, some similar error was happening to me too. To which Yii version did you upgrade? Did you upgrade using Composer?
