### ISSUE TITLE
Error on Streams Monitor page "Creating default object from empty value in"

### ISSUE THREAD

**Issue by btoplak** [AlexanderJLiu/IPTVM#8]
Hi @AlexanderJLiu !

Thanks for this great software, I can see you have invested some time to build this. But I am not sure if this version in GitHub is fully functional at this moment?

Anyway, I successfully installed the IPTVM on Ubuntu 18.04, only with minor issues with Yii compatibility with PHP 7.2, but that was solved easily using Composer update.
I imported SQL dumps for essential tables and the examples.

The app seems to work except the IPTV Monitor->Streams Monitor page (/index.php?r=monitor%2Fstreams-monitor) which gives this error:

```
yii\base\ErrorException: Creating default object from empty value in /var/www/clients/client0/web1/web/controllers/MonitorController.php:210
Stack trace:
#0 /var/www/clients/client0/web1/web/controllers/MonitorController.php(210): yii\base\ErrorHandler->handleError(2, 'Creating defaul...', '/var/www/client...', 210, Array)
#1 [internal function]: app\controllers\MonitorController->actionStreamsMonitor(NULL)
#2 /var/www/clients/client0/web1/web/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/clients/client0/web1/web/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/clients/client0/web1/web/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('streams-monitor', Array)
#5 /var/www/clients/client0/web1/web/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('monitor/streams...', Array)
#6 /var/www/clients/client0/web1/web/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 /var/www/clients/client0/web1/web/web/index.php(12): yii\base\Application->run()
#8 {main}
```

**Comment by AlexanderJLiu** [comment]
@btoplak The essential examples are not very complete. If you want to monitor your own server, you should add server by menu  **IPTV Moinitor->Monitor Configuration->Monitored Servers** first. And the streams also need to import to db by yourself(**IPTV Moinitor->Monitor Configuration->Monitored Streams**). Then the error could be solved. But If you want to get the **CPU** and **RAM** info of servers and streams, you should deploy [IPTVAgent](https://github.com/AlexanderJLiu/IPTVAgent) on your server, and use [IPTVStreaming](https://github.com/AlexanderJLiu/IPTVStreaming) to stream your sources.

**Comment by btoplak** [comment]
Hi @AlexanderJLiu and thanks for your fast reply.
Yeah, I thought it is actually just related to the fact that there are no servers on the list. Still, it is worth fixing ;)

And thanks for the tipps about relation with the IPTVAgent and IPTVStreaming apps. I'd recommend to include those details in the Readme, it would help a lot.

Regards!

**Comment by AlexanderJLiu** [comment]
@btoplak Thank you for your suggestion, I'll add these details to README soon. :+1:
