### ISSUE TITLE
Essential documentation?

### ISSUE THREAD

**Issue by btoplak** [AlexanderJLiu/IPTVM#9]
Hi again @AlexanderJLiu !

Can you provide some essential documentation on how this application is intended to be used? How to export the playlist of those streams?
Examples in database are not quite helpful to get me started, to be honest.... so any any directions
would be highly appreciated!

Thanks!

**Comment by AlexanderJLiu** [comment]
@btoplak This app is used to **Manage** some basic info of IPTV like account and product etc, and **Monitor** some basic info of servers and streams like cpu and ram etc. You can also send command to remote server to start|stop|restart IPTVStreaming by socket. As I mentioned in #8， you should add some servers you have and deploy IPTVAgent on your servers.
